kind: ConfigMap
apiVersion: v1
metadata:
  name: news-config
  namespace: newsera
data:
  PORTS: "5003"
  MONGO_URL: "mongodb://mongodb.newsera.svc.cluster.local:27017/newsera"
    
---

kind: Secret
apiVersion: v1
metadata: 
  name: news-secret
  namespace: newsera
type: Opaque
data:
   GEMINI_API_KEY: "QVEuQWI4Uk42SW9PMlNsWDJ3QjQ3WkNHRjNlcy0tV0NzVk41NTdsVHhrMmwtb05VN0w4alE="
   
  

   