# nginx/nginx.conf

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    
    upstream frontend_app {
        server frontend:5173;
    }

    upstream api_gateway_app {
        server api-gateway:5000;
    }

    server {
        listen 80;
        server_name localhost;

        # 1. Route all standard web traffic to the React Frontend
        location / {
            proxy_pass http://frontend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
            proxy_set_header X-Forwarded-Proto $scheme;

            # Required for Vite Hot Module Replacement (WebSockets) in dev mode
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # 2. Route all API traffic to the API Gateway
        location /api/ {
            proxy_pass http://api_gateway_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}